### ISSUE TITLE
Resolving paths wrong in git bash on windows

### ISSUE THREAD

**Issue by marcofranssen** [npm/node-which#50]
When on windows I get following errors from the which library.
```
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\code\my_project\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\code\my_project\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\code\my_project\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\code\my_project\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\code\my_project\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\code\my_project\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\code\my_project\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\code\my_project\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\code\my_project\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\code\my_project\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\code\my_project\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\code\my_project\node_modules\isexe\windows.js:36:5
```

On windows in git bash it should though have paths like this.

```
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/c/code/my_project/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/c/code/my_project/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/c/code/my_project/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /c/code/my_project/node_modules/which/which.js:89:16
gyp verb `which` failed     at /c/code/my_project/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /c/code/my_project/node_modules/isexe/windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/c/code/my_project/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/c/code/my_project/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/c/code/my_project/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /c/code/my_project/node_modules/which/which.js:89:16
gyp verb `which` failed     at /c/code/my_project/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /c/code/my_project/node_modules/isexe/windows.js:36:5
```

**Comment by jclay** [comment]
I'm getting a similar issues as well (with which 1.2.14), albeit I'm getting the error in Powershell as well. The most basic case to reproduce is as follows:


```
λ  yarn which cmd
yarn which v0.27.5
$ "D:\dev\node_modules\.bin\which" "cmd"
'D:\dev\node_modules\.bin\which" "cmd' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

**Comment by pyrsmk** [comment]
Event if the issue is a bit old : just install python2 ;)
